### PR TITLE
Implements Event Stats and Team Events for a year

### PR DESCRIPTION
**Pull request by mlavrent**
This adds functionality to get a team's events for the year from The Blue Alliance. It also adds the feature to pull stats such as OPR, DPR, and CCWM from TBA for a given event.

### CODE REVIEW

**Comment by widavies** [comment]
I merged your pull request

**Comment by mlavrent** [comment]
Awesome

**Comment by widavies** [comment]
Hey just letting you know, I majorly changed the API. It now contains EVERY method on the TBA api docs page. Enjoy! Let me know if you need anything else

**Comment by mlavrent** [comment]
Awesome, thanks! Will take a look soon.

**Pull request merged**
